const GOLD_UPGRADES = [
  {
    id: 'g_quill',
    name: 'Goose Quill',
    desc: 'A well-cut quill from the wing of a grey goose, the scribe\'s most faithful instrument',
    baseCost: 5,
    costMult: 2.3,
    max: 10,
    effect: 'clickAdd',
    val: 1,
  },
  {
    id: 'g_ruling',
    name: 'Parchment Ruling',
    desc: 'Lines ruled into the vellum leave traces of red ink. Each red word earns 1 extra denarius when the page turns.',
    baseCost: 10,
    costMult: 2.0,
    max: 10,
    effect: 'pageAdd',
    val: 1,
  },
];

const SALT_UPGRADES = [
  {
    id: "s_bonus1",
    name: "Salt Cellar",
    desc: "Permanent +30% bonus to all production",
    baseCost: 1,
    costMult: 2.5,
    max: 10,
    effect: "saltBonus",
    val: 0.3,
  },
  {
    id: "s_start1",
    name: "Scribe's Provisions",
    desc: "Begin each codex with denarii to hire an apprentice",
    baseCost: 2,
    costMult: 3.0,
    max: 5,
    effect: "startGold",
    val: 50,
  },
  {
    id: "s_pages1",
    name: "Prepared Vellum",
    desc: "+1 denarius per page across all codices",
    baseCost: 3,
    costMult: 2.8,
    max: 8,
    effect: "goldPerPage",
    val: 1,
  },
  {
    id: "s_auto1",
    name: "Eternal Scriptorium",
    desc: "Permanently doubles letters per second",
    baseCost: 5,
    costMult: 3.5,
    max: 5,
    effect: "autoMult",
    val: 2,
  },
  {
    id: "s_click1",
    name: "Golden Quill",
    desc: "Permanently doubles letters per keystroke",
    baseCost: 5,
    costMult: 3.5,
    max: 5,
    effect: "clickPermMult",
    val: 2,
  },
  {
    id: "s_capital",
    name: "Illuminated Capital",
    desc: "Adds the large capital letter to each folio page",
    baseCost: 2,
    costMult: 1,
    max: 1,
    effect: "capital",
    val: 1,
  },
  {
    id: "s_capital2",
    name: "Golden Capital",
    desc: "Adorns the capital with gold leaf and an ornate border",
    baseCost: 8,
    costMult: 1,
    max: 1,
    effect: "capital",
    val: 2,
  },
];

export { GOLD_UPGRADES, SALT_UPGRADES };
