import type { GoldUpgrade, SaltUpgrade } from './upgrades.types';

const GOLD_UPGRADES: GoldUpgrade[] = [
  {
    id: 'g_quill',
    name: 'Goose Quill',
    desc: 'A well-cut quill from the wing of a grey goose, the scribe\'s most faithful instrument.',
    baseCost: 5,
    costMult: 2.3,
    max: 10,
    effect: 'clickAdd',
    val: 1,
  },
  {
    id: 'g_ruling',
    name: 'Parchment Ruling',
    desc: 'Lines ruled into the vellum leave traces of red ink. Each red word earns 1 extra Đ when the page turns.',
    baseCost: 10,
    costMult: 2.0,
    max: 10,
    effect: 'pageAdd',
    val: 1,
  },
  {
    id: 'g_apprentice',
    name: 'Apprentice Scribe',
    desc: 'A young novice copies alongside you, adding letters to the page without tiring.',
    baseCost: 20,
    costMult: 2.5,
    max: 10,
    effect: 'autoAdd',
    val: 2,
    unlocksAt: 1,
  },
  {
    id: 'g_lectern',
    name: 'Brass Lectern',
    desc: 'A heavy lectern steadies the codex and improves the angle of the quill, multiplying every stroke.',
    baseCost: 150,
    costMult: 3.0,
    max: 5,
    effect: 'clickMult',
    val: 1.5,
    unlocksAt: 2,
  },
];

const SALT_UPGRADES: SaltUpgrade[] = [
  {
    id: 's_benefice',
    name: 'Benefice',
    desc: 'A permanent grant from the scriptorium. Each level raises all production by 10%.',
    baseCost: 1,
    costMult: 2.5,
    max: 10,
    effect: 'saltBonus',
    val: 0.1,
  },
  {
    id: 's_provisions',
    name: 'Scribe\'s Provisions',
    desc: 'Salt stored in the cellar funds the next codex. Each level starts you with 50 Đ after binding.',
    baseCost: 3,
    costMult: 2.0,
    max: 5,
    effect: 'startingGold',
    val: 50,
    unlocksAt: 2,
  },
  {
    id: 's_vellum',
    name: 'Prepared Vellum',
    desc: 'Vellum scraped and stretched to perfection. Each page completed earns 1 extra Đ per level.',
    baseCost: 5,
    costMult: 2.0,
    max: 8,
    effect: 'goldPerPage',
    val: 1,
    unlocksAt: 3,
  },
  {
    id: 's_scriptorium',
    name: 'Eternal Scriptorium',
    desc: 'The scriptorium never sleeps. All automatic scribes work twice as fast per level.',
    baseCost: 15,
    costMult: 3.0,
    max: 3,
    effect: 'autoMult',
    val: 2,
    unlocksAt: 5,
  },
  {
    id: 's_golden_quill',
    name: 'Golden Quill',
    desc: 'A quill tipped in gold, its every stroke worth twice the rest.',
    baseCost: 25,
    costMult: 3.5,
    max: 3,
    effect: 'clickMult',
    val: 2,
    unlocksAt: 8,
  },
];

export { GOLD_UPGRADES, SALT_UPGRADES };
